// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1210:Using directives should be ordered alphabetically by namespace", Justification = "Autogenerated EF Core migrations", Scope = "module")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "Autogenerated EF Core migrations", Scope = "namespaceanddescendants", Target = "~N:VocabularyApp.Persistence.MsSql.Migrations")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Autogenerated EF Core migrations", Scope = "namespaceanddescendants", Target = "~N:VocabularyApp.Persistence.MsSql.Migrations")]
[assembly: SuppressMessage("Style", "IDE0161:Convert to file-scoped namespace", Justification = "Autogenerated EF Core migrations", Scope = "namespaceanddescendants", Target = "~N:VocabularyApp.Persistence.MsSql.Migrations")]
